spring:
  profiles:
    active: proc
  thymeleaf:
    #    开发时关闭缓存,上线时开启缓存减少服务端压力
    cache: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  http:
    encoding:
      charset: UTF-8
mybatis:
  mapper-locations: classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 80
  servlet:
    context-path: /blog
logging:
  level:
    root: info