spring:
  data:
    elasticsearch:
      cluster-nodes: www.vicyor.com:9300
      properties:
        transport:
          tcp:
            connect_timeout: 60s
      cluster-name: docker-cluster
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: vicyor123456
    url: jdbc:mysql://www.vicyor.com:3306/blog
  thymeleaf:
#    开发时关闭缓存,上线时开启缓存减少服务端压力
    cache: false
mybatis:
  mapper-locations: classpath:mapper/**.xml
security:
  oauth2:
    client:
      client-id: blog
      client-secret: blog
      user-authorization-uri: http://127.0.0.1:8080/auth/oauth/authorize
      access-token-uri: http://127.0.0.1:8080/auth/oauth/token
    resource:
      jwk:
        key-set-uri: http://127.0.0.1:8080/auth/oauth/token_key
server:
  port: 80
  servlet:
    context-path: /blog