spring:
  thymeleaf:
    cache: false
security:
  oauth2:
    client:
      client-id: blog
      client-secret: blog
      user-authorization-uri: http://127.0.0.1:8080/auth/oauth/authorize
      access-token-uri: http://127.0.0.1:8080/auth/oauth/token
    resource:
      jwk:
        key-set-uri: http://127.0.0.1:8080/auth/oauth/token_key