spring:
  data:
    elasticsearch:
      cluster-nodes: www.vicyor.com:9300
      properties:
        transport:
          tcp:
            connect_timeout: 60s
      cluster-name: docker-cluster
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: vicyor123456
    url: jdbc:mysql://www.vicyor.com:3306/blog
mybatis:
  mapper-locations: classpath:mapper/**.xml