spring:
  data:
    elasticsearch:
      cluster-nodes: 106.13.74.154:9300
      properties:
        transport:
          tcp:
            connect_timeout: 60s
      cluster-name: docker-cluster
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: vicyor123456
    url: jdbc:mysql://106.13.74.154:3306/blog
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
security:
  oauth2:
    client:
      client-id: blog
      client-secret: blog
      user-authorization-uri: http://127.0.0.1:8080/auth/oauth/authorize
      access-token-uri: http://127.0.0.1:8080/auth/oauth/token
    resource:
      jwk:
        key-set-uri: http://127.0.0.1:8080/auth/oauth/token_key