sso:
  authorization:
    signingKey: 007
    clients:
      blog:
        clientId: blog
        clientSecret: blog
        authorizedGrantTypes: authorization_code,refresh_token
        redirectUri: http://127.0.0.1/login
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: vicyor123456
    url: jdbc:mysql://www.vicyor.com:3306/blog
server:
  port: 8080