sso:
  authorization:
    clients:
      blog:
        clientId: blog
        clientSecret: blog
        authorizedGrantTypes: authorization_code,refresh_token
        redirectUri:
                         - http://127.0.0.1/blog/login
                         - http://www.vicyor.com/blog/login
                         - http://129.204.72.141/blog/login
                         - http://192.168.1.3/blog/login
                         - http://192.168.1.2/blog/login
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: vicyor123456
    url: jdbc:mysql://www.vicyor.com:3306/blog
  thymeleaf:
    cache: false
server:
  port: 8080
  servlet:
    context-path: /auth