#这是用户统计详细信息模块
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: vicyor123456
    url: jdbc:mysql://106.13.74.154:3306/blog
    hikari:
      maximum-pool-size: 10
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  http:
    encoding:
      charset: UTF-8
  data:
    elasticsearch:
      cluster-nodes: 106.13.74.154:9300
      properties:
        transport:
          tcp:
            connect_timeout: 60s
      cluster-name: docker-cluster
server:
  port: 9090
  servlet:
    context-path: /user
mybatis:
  mapper-locations: classpath:mapper/**.xml
  configuration:
    #    开启驼峰命名
    map-underscore-to-camel-case: true
